.TH man 1 "12 May 2020" "1.0" "lilui user interface toolkit man page"

.SH NAME
lilui user interface toolkit

.SH DESCRIPTION
lilui is a small user interface toolkit for C and X11 based applications.
The API is simple and inspired by immediate-mode libraries like Nuklear
and Dear ImGUI.

.SH THEMES
A lilui theme defines the color scheme and fonts used in a lilui app. A
theme file can be specified using the LILUI_THEME environmental variable.
This will be loaded by lilui applications on startup, unless they use
a custom theme.

.SH SEE ALSO
lilwm(1)

.SH AUTHOR
swissChili (swisschili.sh, github.com/swissChili)
