.TH man 1 "12 May 2020" "1.0" "lilui user interface toolkit man page"

.SH NAME
lilui user interface toolkit

.SH DESCRIPTION
lilui is a small user interface toolkit for C and X11 based applications.
The API is simple and inspired by immediate-mode libraries like Nuklear
and Dear ImGUI.

.SH SEE ALSO
lilwm(1)

.SH AUTHOR
swissChili (swisschili.sh, github.com/swissChili)
