.TH man 1 "11 May 2020" "1.0" "lilwm window manager man page"

.SH NAME
lilwm window manager

.SH SYNOPSIS
lilwm [lilwmrc]
.RS 6
lilwmrc \- path to lilwm configuration file

.SH DESCRIPTION
lilwm is a simple window manager for X11.

.SH COMMANDS
Commands are used to communicate with lilwm.
These commands can be invoked based on keyboard shortcuts (see
lilwmrc(5)), or through a socket [TODO].

.SH SEE ALSO
lilwmrc(5)

.SH AUTHOR
swissChili (swisschili.sh, github.com/swissChili)
